name: variables and Workflows
on: 
  push:
  schedule:
    - cron: "* */1 * * *"


env:
  Container_Registery: docker.io
  image_name: abcd
  docker_name: sanchit


jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        run: echo docker build -t ${{env.Container_Registery}}/${{env.docker_name}}/${{env.image_name}}:latest .
      
      - name: docker login
        run: echo docker login --username=${{env.docker_name}} --password=${{secrets.DOCKER_PASSWORD}} 
      
      - name: docker push
        run: echo docker push ${{env.Container_Registery}}/${{env.docker_name}}/${{env.image_name}}:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
    - name: docker run
      run: |
          echo docker run -d -p 80:80 ${{env.Container_Registery}}/${{env.image_name}}/${{env.image_name}}:latest
          sleep 600
