name: First Workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: message
        run: echo "Hello there"

      - name: Second step
        run: ls
      
      - name: third step
        run: cat README.md