name: First Workflow
on: 
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: mutliple commands to run
        run: |
          echo "Hello there"
          ls -ar
          cat README.md
