name: generate ascii artWork

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay library
        run: sudo apt-get install cowsay -y

      - name: execture cowsay command
        run: cowsay -f dragon "Hi from dragon sanchit" >> dragon.txt

      - name: Upload the dragon file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
  
  Second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: download the file
        uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: test file exists
        run: grep -i "dragon" dragon.txt
      
  deploy_job:
    needs: Second_job
    runs-on: ubuntu-latest
    steps:
      - name: download txt file
        uses: actions/download-artifact@v4
        with:
          name: dragon-file
          
      - name: read file
        run: cat dragon.txt

