name: generate ascii artWork

on: push

jobs:
  first_job:
  runs-on: ubuntu-latest
  steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: install cowsay library
      run: sudo apt-get install cowsay -y

    - name: execture cowsay command
      run: cowsay -f dragon "Hi from dragon sanchit" >> dragon.txt

    - name: test file exists
      run: grep -i "dragon" dragon.txt

    - name: read file
      run: cat dragon.txt

    - name: files in repo
      run: ls -a
      
